/**
 * NCAAM team slug → { school, nickname } map.
 * Auto-generated from ESPN API (2026-03-04).
 * Covers all 362 NCAAM teams on ESPN.
 * 
 * school: The university/college name (e.g., "Oral Roberts")
 * nickname: The team mascot (e.g., "Golden Eagles")
 */

export interface TeamName {
  school: string;
  nickname: string;
}

export const TEAM_NAMES: Record<string, TeamName> = {
  abilene_chrstn: { school: "Abilene Christian", nickname: "Wildcats" },
  air_force: { school: "Air Force", nickname: "Falcons" },
  akron: { school: "Akron", nickname: "Zips" },
  alabama_am: { school: "Alabama A&M", nickname: "Bulldogs" },
  alabama: { school: "Alabama", nickname: "Crimson Tide" },
  alabama_st: { school: "Alabama State", nickname: "Hornets" },
  alcorn_st: { school: "Alcorn State", nickname: "Braves" },
  american: { school: "American University", nickname: "Eagles" },
  app_state: { school: "App State", nickname: "Mountaineers" },
  arizona_st: { school: "Arizona State", nickname: "Sun Devils" },
  arizona: { school: "Arizona", nickname: "Wildcats" },
  arkansas: { school: "Arkansas", nickname: "Razorbacks" },
  arkansas_st: { school: "Arkansas State", nickname: "Red Wolves" },
  arpine_bluff: { school: "Arkansas-Pine Bluff", nickname: "Golden Lions" },
  army: { school: "Army", nickname: "Black Knights" },
  auburn: { school: "Auburn", nickname: "Tigers" },
  austin_peay: { school: "Austin Peay", nickname: "Governors" },
  ball_state: { school: "Ball State", nickname: "Cardinals" },
  baylor: { school: "Baylor", nickname: "Bears" },
  bellarmine: { school: "Bellarmine", nickname: "Knights" },
  belmont: { school: "Belmont", nickname: "Bruins" },
  bethune: { school: "Bethune-Cookman", nickname: "Wildcats" },
  binghamton: { school: "Binghamton", nickname: "Bearcats" },
  boise_st: { school: "Boise State", nickname: "Broncos" },
  boston_college: { school: "Boston College", nickname: "Eagles" },
  boston_u: { school: "Boston University", nickname: "Terriers" },
  bowling_green: { school: "Bowling Green", nickname: "Falcons" },
  bradley: { school: "Bradley", nickname: "Braves" },
  brown: { school: "Brown", nickname: "Bears" },
  bryant: { school: "Bryant", nickname: "Bulldogs" },
  bucknell: { school: "Bucknell", nickname: "Bison" },
  buffalo: { school: "Buffalo", nickname: "Bulls" },
  butler: { school: "Butler", nickname: "Bulldogs" },
  byu: { school: "BYU", nickname: "Cougars" },
  cal_poly: { school: "Cal Poly", nickname: "Mustangs" },
  bakersfield: { school: "Cal State Bakersfield", nickname: "Roadrunners" },
  fullerton: { school: "Cal State Fullerton", nickname: "Titans" },
  csu_northridge: { school: "Cal State Northridge", nickname: "Matadors" },
  ca_baptist: { school: "California Baptist", nickname: "Lancers" },
  california: { school: "California", nickname: "Golden Bears" },
  campbell: { school: "Campbell", nickname: "Fighting Camels" },
  canisius: { school: "Canisius", nickname: "Golden Griffins" },
  c_arkansas: { school: "Central Arkansas", nickname: "Bears" },
  c_connecticut: { school: "Central Connecticut", nickname: "Blue Devils" },
  c_michigan: { school: "Central Michigan", nickname: "Chippewas" },
  charleston: { school: "Charleston", nickname: "Cougars" },
  charleston_so: { school: "Charleston Southern", nickname: "Buccaneers" },
  charlotte: { school: "Charlotte", nickname: "49ers" },
  chattanooga: { school: "Chattanooga", nickname: "Mocs" },
  chicago_st: { school: "Chicago State", nickname: "Cougars" },
  cincinnati: { school: "Cincinnati", nickname: "Bearcats" },
  clemson: { school: "Clemson", nickname: "Tigers" },
  cleveland_st: { school: "Cleveland State", nickname: "Vikings" },
  coastal: { school: "Coastal Carolina", nickname: "Chanticleers" },
  colgate: { school: "Colgate", nickname: "Raiders" },
  colorado: { school: "Colorado", nickname: "Buffaloes" },
  colorado_st: { school: "Colorado State", nickname: "Rams" },
  columbia: { school: "Columbia", nickname: "Lions" },
  coppin_st: { school: "Coppin State", nickname: "Eagles" },
  cornell: { school: "Cornell", nickname: "Big Red" },
  creighton: { school: "Creighton", nickname: "Bluejays" },
  dartmouth: { school: "Dartmouth", nickname: "Big Green" },
  davidson: { school: "Davidson", nickname: "Wildcats" },
  dayton: { school: "Dayton", nickname: "Flyers" },
  delaware: { school: "Delaware", nickname: "Blue Hens" },
  delaware_st: { school: "Delaware State", nickname: "Hornets" },
  denver: { school: "Denver", nickname: "Pioneers" },
  depaul: { school: "DePaul", nickname: "Blue Demons" },
  detroit_mercy: { school: "Detroit Mercy", nickname: "Titans" },
  drake: { school: "Drake", nickname: "Bulldogs" },
  drexel: { school: "Drexel", nickname: "Dragons" },
  duke: { school: "Duke", nickname: "Blue Devils" },
  duquesne: { school: "Duquesne", nickname: "Dukes" },
  east_carolina: { school: "East Carolina", nickname: "Pirates" },
  etsu: { school: "East Tennessee State", nickname: "Buccaneers" },
  e_texas_am: { school: "East Texas A&M", nickname: "Lions" },
  e_illinois: { school: "Eastern Illinois", nickname: "Panthers" },
  e_kentucky: { school: "Eastern Kentucky", nickname: "Colonels" },
  e_michigan: { school: "Eastern Michigan", nickname: "Eagles" },
  e_washington: { school: "Eastern Washington", nickname: "Eagles" },
  elon: { school: "Elon", nickname: "Phoenix" },
  evansville: { school: "Evansville", nickname: "Purple Aces" },
  fairfield: { school: "Fairfield", nickname: "Stags" },
  fdu: { school: "Fairleigh Dickinson", nickname: "Knights" },
  florida_am: { school: "Florida A&M", nickname: "Rattlers" },
  fau: { school: "Florida Atlantic", nickname: "Owls" },
  florida: { school: "Florida", nickname: "Gators" },
  fgcu: { school: "Florida Gulf Coast", nickname: "Eagles" },
  fiu: { school: "Florida International", nickname: "Panthers" },
  florida_st: { school: "Florida State", nickname: "Seminoles" },
  fordham: { school: "Fordham", nickname: "Rams" },
  fresno_st: { school: "Fresno State", nickname: "Bulldogs" },
  furman: { school: "Furman", nickname: "Paladins" },
  gardnerwebb: { school: "Gardner-Webb", nickname: "Runnin' Bulldogs" },
  george_mason: { school: "George Mason", nickname: "Patriots" },
  g_washington: { school: "George Washington", nickname: "Revolutionaries" },
  georgetown: { school: "Georgetown", nickname: "Hoyas" },
  georgia: { school: "Georgia", nickname: "Bulldogs" },
  ga_southern: { school: "Georgia Southern", nickname: "Eagles" },
  georgia_st: { school: "Georgia State", nickname: "Panthers" },
  georgia_tech: { school: "Georgia Tech", nickname: "Yellow Jackets" },
  gonzaga: { school: "Gonzaga", nickname: "Bulldogs" },
  grambling: { school: "Grambling", nickname: "Tigers" },
  grand_canyon: { school: "Grand Canyon", nickname: "Lopes" },
  green_bay: { school: "Green Bay", nickname: "Phoenix" },
  hampton: { school: "Hampton", nickname: "Pirates" },
  harvard: { school: "Harvard", nickname: "Crimson" },
  hawaii: { school: "Hawai'i", nickname: "Rainbow Warriors" },
  high_point: { school: "High Point", nickname: "Panthers" },
  hofstra: { school: "Hofstra", nickname: "Pride" },
  holy_cross: { school: "Holy Cross", nickname: "Crusaders" },
  hou_christian: { school: "Houston Christian", nickname: "Huskies" },
  houston: { school: "Houston", nickname: "Cougars" },
  howard: { school: "Howard", nickname: "Bison" },
  idaho_st: { school: "Idaho State", nickname: "Bengals" },
  idaho: { school: "Idaho", nickname: "Vandals" },
  illinois: { school: "Illinois", nickname: "Fighting Illini" },
  illinois_st: { school: "Illinois State", nickname: "Redbirds" },
  incarnate_word: { school: "Incarnate Word", nickname: "Cardinals" },
  indiana: { school: "Indiana", nickname: "Hoosiers" },
  indiana_st: { school: "Indiana State", nickname: "Sycamores" },
  iona: { school: "Iona", nickname: "Gaels" },
  iowa: { school: "Iowa", nickname: "Hawkeyes" },
  iowa_state: { school: "Iowa State", nickname: "Cyclones" },
  iu_indy: { school: "IU Indianapolis", nickname: "Jaguars" },
  jackson_st: { school: "Jackson State", nickname: "Tigers" },
  jacksonville: { school: "Jacksonville", nickname: "Dolphins" },
  jax_state: { school: "Jacksonville State", nickname: "Gamecocks" },
  james_madison: { school: "James Madison", nickname: "Dukes" },
  kansas_city: { school: "Kansas City", nickname: "Roos" },
  kansas: { school: "Kansas", nickname: "Jayhawks" },
  kansas_st: { school: "Kansas State", nickname: "Wildcats" },
  kennesaw_st: { school: "Kennesaw State", nickname: "Owls" },
  kent_state: { school: "Kent State", nickname: "Golden Flashes" },
  kentucky: { school: "Kentucky", nickname: "Wildcats" },
  la_salle: { school: "La Salle", nickname: "Explorers" },
  lafayette: { school: "Lafayette", nickname: "Leopards" },
  lamar: { school: "Lamar", nickname: "Cardinals" },
  le_moyne: { school: "Le Moyne", nickname: "Dolphins" },
  lehigh: { school: "Lehigh", nickname: "Mountain Hawks" },
  liberty: { school: "Liberty", nickname: "Flames" },
  lipscomb: { school: "Lipscomb", nickname: "Bisons" },
  little_rock: { school: "Little Rock", nickname: "Trojans" },
  long_beach_st: { school: "Long Beach State", nickname: "Beach" },
  long_island: { school: "Long Island University", nickname: "Sharks" },
  longwood: { school: "Longwood", nickname: "Lancers" },
  louisiana: { school: "Louisiana", nickname: "Ragin' Cajuns" },
  louisiana_tech: { school: "Louisiana Tech", nickname: "Bulldogs" },
  louisville: { school: "Louisville", nickname: "Cardinals" },
  loyola_chicago: { school: "Loyola Chicago", nickname: "Ramblers" },
  loyola_md: { school: "Loyola Maryland", nickname: "Greyhounds" },
  lmu: { school: "Loyola Marymount", nickname: "Lions" },
  lsu: { school: "LSU", nickname: "Tigers" },
  maine: { school: "Maine", nickname: "Black Bears" },
  manhattan: { school: "Manhattan", nickname: "Jaspers" },
  marist: { school: "Marist", nickname: "Red Foxes" },
  marquette: { school: "Marquette", nickname: "Golden Eagles" },
  marshall: { school: "Marshall", nickname: "Thundering Herd" },
  md_eastern: { school: "Maryland Eastern Shore", nickname: "Hawks" },
  maryland: { school: "Maryland", nickname: "Terrapins" },
  umass: { school: "Massachusetts", nickname: "Minutemen" },
  mcneese: { school: "McNeese", nickname: "Cowboys" },
  memphis: { school: "Memphis", nickname: "Tigers" },
  mercer: { school: "Mercer", nickname: "Bears" },
  mercyhurst: { school: "Mercyhurst", nickname: "Lakers" },
  merrimack: { school: "Merrimack", nickname: "Warriors" },
  miami_oh: { school: "Miami (OH)", nickname: "RedHawks" },
  miami: { school: "Miami", nickname: "Hurricanes" },
  michigan_st: { school: "Michigan State", nickname: "Spartans" },
  michigan: { school: "Michigan", nickname: "Wolverines" },
  mtsu: { school: "Middle Tennessee", nickname: "Blue Raiders" },
  milwaukee: { school: "Milwaukee", nickname: "Panthers" },
  minnesota: { school: "Minnesota", nickname: "Golden Gophers" },
  mississippi_st: { school: "Mississippi State", nickname: "Bulldogs" },
  miss_valley_st: { school: "Mississippi Valley State", nickname: "Delta Devils" },
  missouri_st: { school: "Missouri State", nickname: "Bears" },
  missouri: { school: "Missouri", nickname: "Tigers" },
  monmouth: { school: "Monmouth", nickname: "Hawks" },
  montana: { school: "Montana", nickname: "Grizzlies" },
  montana_st: { school: "Montana State", nickname: "Bobcats" },
  morehead_st: { school: "Morehead State", nickname: "Eagles" },
  morgan_st: { school: "Morgan State", nickname: "Bears" },
  mount_st_marys: { school: "Mount St. Mary's", nickname: "Mountaineers" },
  murray_st: { school: "Murray State", nickname: "Racers" },
  navy: { school: "Navy", nickname: "Midshipmen" },
  nc_state: { school: "NC State", nickname: "Wolfpack" },
  nebraska: { school: "Nebraska", nickname: "Cornhuskers" },
  nevada: { school: "Nevada", nickname: "Wolf Pack" },
  new_hampshire: { school: "New Hampshire", nickname: "Wildcats" },
  new_haven: { school: "New Haven", nickname: "Chargers" },
  new_mexico: { school: "New Mexico", nickname: "Lobos" },
  new_mexico_st: { school: "New Mexico State", nickname: "Aggies" },
  new_orleans: { school: "New Orleans", nickname: "Privateers" },
  niagara: { school: "Niagara", nickname: "Purple Eagles" },
  nicholls: { school: "Nicholls", nickname: "Colonels" },
  njit: { school: "NJIT", nickname: "Highlanders" },
  norfolk_st: { school: "Norfolk State", nickname: "Spartans" },
  north_alabama: { school: "North Alabama", nickname: "Lions" },
  nc_at: { school: "North Carolina A&T", nickname: "Aggies" },
  nc_central: { school: "North Carolina Central", nickname: "Eagles" },
  north_carolina: { school: "North Carolina", nickname: "Tar Heels" },
  north_dakota: { school: "North Dakota", nickname: "Fighting Hawks" },
  n_dakota_st: { school: "North Dakota State", nickname: "Bison" },
  north_florida: { school: "North Florida", nickname: "Ospreys" },
  north_texas: { school: "North Texas", nickname: "Mean Green" },
  northeastern: { school: "Northeastern", nickname: "Huskies" },
  n_arizona: { school: "Northern Arizona", nickname: "Lumberjacks" },
  n_colorado: { school: "Northern Colorado", nickname: "Bears" },
  n_illinois: { school: "Northern Illinois", nickname: "Huskies" },
  northern_iowa: { school: "Northern Iowa", nickname: "Panthers" },
  n_kentucky: { school: "Northern Kentucky", nickname: "Norse" },
  nwestern_st: { school: "Northwestern State", nickname: "Demons" },
  northwestern: { school: "Northwestern", nickname: "Wildcats" },
  notre_dame: { school: "Notre Dame", nickname: "Fighting Irish" },
  oakland: { school: "Oakland", nickname: "Golden Grizzlies" },
  ohio: { school: "Ohio", nickname: "Bobcats" },
  ohio_state: { school: "Ohio State", nickname: "Buckeyes" },
  oklahoma: { school: "Oklahoma", nickname: "Sooners" },
  oklahoma_st: { school: "Oklahoma State", nickname: "Cowboys" },
  old_dominion: { school: "Old Dominion", nickname: "Monarchs" },
  ole_miss: { school: "Ole Miss", nickname: "Rebels" },
  omaha: { school: "Omaha", nickname: "Mavericks" },
  oral_roberts: { school: "Oral Roberts", nickname: "Golden Eagles" },
  oregon: { school: "Oregon", nickname: "Ducks" },
  oregon_st: { school: "Oregon State", nickname: "Beavers" },
  pacific: { school: "Pacific", nickname: "Tigers" },
  penn_state: { school: "Penn State", nickname: "Nittany Lions" },
  penn: { school: "Pennsylvania", nickname: "Quakers" },
  pepperdine: { school: "Pepperdine", nickname: "Waves" },
  pitt: { school: "Pittsburgh", nickname: "Panthers" },
  portland: { school: "Portland", nickname: "Pilots" },
  portland_st: { school: "Portland State", nickname: "Vikings" },
  prairie_view: { school: "Prairie View A&M", nickname: "Panthers" },
  presbyterian: { school: "Presbyterian", nickname: "Blue Hose" },
  princeton: { school: "Princeton", nickname: "Tigers" },
  providence: { school: "Providence", nickname: "Friars" },
  purdue: { school: "Purdue", nickname: "Boilermakers" },
  purdue_fw: { school: "Purdue Fort Wayne", nickname: "Mastodons" },
  quinnipiac: { school: "Quinnipiac", nickname: "Bobcats" },
  radford: { school: "Radford", nickname: "Highlanders" },
  rhode_island: { school: "Rhode Island", nickname: "Rams" },
  rice: { school: "Rice", nickname: "Owls" },
  richmond: { school: "Richmond", nickname: "Spiders" },
  rider: { school: "Rider", nickname: "Broncs" },
  robert_morris: { school: "Robert Morris", nickname: "Colonials" },
  rutgers: { school: "Rutgers", nickname: "Scarlet Knights" },
  sacramento_st: { school: "Sacramento State", nickname: "Hornets" },
  sacred_heart: { school: "Sacred Heart", nickname: "Pioneers" },
  saint_francis: { school: "Saint Francis", nickname: "Red Flash" },
  saint_josephs: { school: "Saint Joseph's", nickname: "Hawks" },
  saint_louis: { school: "Saint Louis", nickname: "Billikens" },
  saint_marys: { school: "Saint Mary's", nickname: "Gaels" },
  saint_peters: { school: "Saint Peter's", nickname: "Peacocks" },
  sam_houston: { school: "Sam Houston", nickname: "Bearkats" },
  samford: { school: "Samford", nickname: "Bulldogs" },
  san_diego_st: { school: "San Diego State", nickname: "Aztecs" },
  san_diego: { school: "San Diego", nickname: "Toreros" },
  san_francisco: { school: "San Francisco", nickname: "Dons" },
  san_jos_st: { school: "San José State", nickname: "Spartans" },
  santa_clara: { school: "Santa Clara", nickname: "Broncos" },
  se_louisiana: { school: "SE Louisiana", nickname: "Lions" },
  seattle_u: { school: "Seattle U", nickname: "Redhawks" },
  seton_hall: { school: "Seton Hall", nickname: "Pirates" },
  siena: { school: "Siena", nickname: "Saints" },
  siue: { school: "SIU Edwardsville", nickname: "Cougars" },
  smu: { school: "SMU", nickname: "Mustangs" },
  south_alabama: { school: "South Alabama", nickname: "Jaguars" },
  south_carolina: { school: "South Carolina", nickname: "Gamecocks" },
  sc_state: { school: "South Carolina State", nickname: "Bulldogs" },
  sc_upstate: { school: "South Carolina Upstate", nickname: "Spartans" },
  south_dakota: { school: "South Dakota", nickname: "Coyotes" },
  s_dakota_st: { school: "South Dakota State", nickname: "Jackrabbits" },
  south_florida: { school: "South Florida", nickname: "Bulls" },
  se_missouri: { school: "Southeast Missouri State", nickname: "Redhawks" },
  s_illinois: { school: "Southern Illinois", nickname: "Salukis" },
  southern: { school: "Southern", nickname: "Jaguars" },
  southern_miss: { school: "Southern Miss", nickname: "Golden Eagles" },
  southern_utah: { school: "Southern Utah", nickname: "Thunderbirds" },
  st_bonaventure: { school: "St. Bonaventure", nickname: "Bonnies" },
  st_johns: { school: "St. John's", nickname: "Red Storm" },
  st_thomas_mn: { school: "St. Thomas-Minnesota", nickname: "Tommies" },
  stanford: { school: "Stanford", nickname: "Cardinal" },
  sf_austin: { school: "Stephen F. Austin", nickname: "Lumberjacks" },
  stetson: { school: "Stetson", nickname: "Hatters" },
  stonehill: { school: "Stonehill", nickname: "Skyhawks" },
  stony_brook: { school: "Stony Brook", nickname: "Seawolves" },
  syracuse: { school: "Syracuse", nickname: "Orange" },
  tarleton_st: { school: "Tarleton State", nickname: "Texans" },
  tcu: { school: "TCU", nickname: "Horned Frogs" },
  temple: { school: "Temple", nickname: "Owls" },
  tennessee_st: { school: "Tennessee State", nickname: "Tigers" },
  tennessee_tech: { school: "Tennessee Tech", nickname: "Golden Eagles" },
  tennessee: { school: "Tennessee", nickname: "Volunteers" },
  texas_am: { school: "Texas A&M", nickname: "Aggies" },
  texas_amcc: { school: "Texas A&M-Corpus Christi", nickname: "Islanders" },
  texas: { school: "Texas", nickname: "Longhorns" },
  texas_southern: { school: "Texas Southern", nickname: "Tigers" },
  texas_st: { school: "Texas State", nickname: "Bobcats" },
  texas_tech: { school: "Texas Tech", nickname: "Red Raiders" },
  the_citadel: { school: "The Citadel", nickname: "Bulldogs" },
  toledo: { school: "Toledo", nickname: "Rockets" },
  towson: { school: "Towson", nickname: "Tigers" },
  troy: { school: "Troy", nickname: "Trojans" },
  tulane: { school: "Tulane", nickname: "Green Wave" },
  tulsa: { school: "Tulsa", nickname: "Golden Hurricane" },
  uab: { school: "UAB", nickname: "Blazers" },
  ualbany: { school: "UAlbany", nickname: "Great Danes" },
  uc_davis: { school: "UC Davis", nickname: "Aggies" },
  uc_irvine: { school: "UC Irvine", nickname: "Anteaters" },
  uc_riverside: { school: "UC Riverside", nickname: "Highlanders" },
  uc_san_diego: { school: "UC San Diego", nickname: "Tritons" },
  santa_barbara: { school: "UC Santa Barbara", nickname: "Gauchos" },
  ucf: { school: "UCF", nickname: "Knights" },
  ucla: { school: "UCLA", nickname: "Bruins" },
  uconn: { school: "UConn", nickname: "Huskies" },
  uic: { school: "UIC", nickname: "Flames" },
  ul_monroe: { school: "UL Monroe", nickname: "Warhawks" },
  umass_lowell: { school: "UMass Lowell", nickname: "River Hawks" },
  umbc: { school: "UMBC", nickname: "Retrievers" },
  unc_asheville: { school: "UNC Asheville", nickname: "Bulldogs" },
  unc_greensboro: { school: "UNC Greensboro", nickname: "Spartans" },
  unc_wilmington: { school: "UNC Wilmington", nickname: "Seahawks" },
  unlv: { school: "UNLV", nickname: "Rebels" },
  usc: { school: "USC", nickname: "Trojans" },
  ut_arlington: { school: "UT Arlington", nickname: "Mavericks" },
  ut_martin: { school: "UT Martin", nickname: "Skyhawks" },
  ut_rio_grande: { school: "UT Rio Grande Valley", nickname: "Vaqueros" },
  utah_state: { school: "Utah State", nickname: "Aggies" },
  utah_tech: { school: "Utah Tech", nickname: "Trailblazers" },
  utah: { school: "Utah", nickname: "Utes" },
  utah_valley: { school: "Utah Valley", nickname: "Wolverines" },
  utep: { school: "UTEP", nickname: "Miners" },
  utsa: { school: "UTSA", nickname: "Roadrunners" },
  valparaiso: { school: "Valparaiso", nickname: "Beacons" },
  vanderbilt: { school: "Vanderbilt", nickname: "Commodores" },
  vcu: { school: "VCU", nickname: "Rams" },
  vermont: { school: "Vermont", nickname: "Catamounts" },
  villanova: { school: "Villanova", nickname: "Wildcats" },
  virginia: { school: "Virginia", nickname: "Cavaliers" },
  virginia_tech: { school: "Virginia Tech", nickname: "Hokies" },
  vmi: { school: "VMI", nickname: "Keydets" },
  wagner: { school: "Wagner", nickname: "Seahawks" },
  wake_forest: { school: "Wake Forest", nickname: "Demon Deacons" },
  washington: { school: "Washington", nickname: "Huskies" },
  washington_st: { school: "Washington State", nickname: "Cougars" },
  weber_st: { school: "Weber State", nickname: "Wildcats" },
  west_georgia: { school: "West Georgia", nickname: "Wolves" },
  west_virginia: { school: "West Virginia", nickname: "Mountaineers" },
  w_carolina: { school: "Western Carolina", nickname: "Catamounts" },
  w_illinois: { school: "Western Illinois", nickname: "Leathernecks" },
  western_ky: { school: "Western Kentucky", nickname: "Hilltoppers" },
  w_michigan: { school: "Western Michigan", nickname: "Broncos" },
  wichita_st: { school: "Wichita State", nickname: "Shockers" },
  william_mary: { school: "William & Mary", nickname: "Tribe" },
  winthrop: { school: "Winthrop", nickname: "Eagles" },
  wisconsin: { school: "Wisconsin", nickname: "Badgers" },
  wofford: { school: "Wofford", nickname: "Terriers" },
  wright_st: { school: "Wright State", nickname: "Raiders" },
  wyoming: { school: "Wyoming", nickname: "Cowboys" },
  xavier: { school: "Xavier", nickname: "Musketeers" },
  yale: { school: "Yale", nickname: "Bulldogs" },
  youngstown_st: { school: "Youngstown State", nickname: "Penguins" },
};

// DB slug aliases — maps DB-stored slugs to proper display names
// Needed because the DB slugs differ from the shortDisplayName-based slugs above.
const DB_SLUG_NICKNAME_ALIASES: Record<string, TeamName> = {
  florida_state: { school: "Florida State", nickname: "Seminoles" },
  chicago_state: { school: "Chicago State", nickname: "Cougars" },
  wright_state: { school: "Wright State", nickname: "Raiders" },
  youngstown_state: { school: "Youngstown State", nickname: "Penguins" },
  eastern_illinois: { school: "Eastern Illinois", nickname: "Panthers" },
  eastern_kentucky: { school: "Eastern Kentucky", nickname: "Colonels" },
  northern_kentucky: { school: "Northern Kentucky", nickname: "Norse" },
  south_carolina_upstate: { school: "SC Upstate", nickname: "Spartans" },
  george_washington: { school: "George Washington", nickname: "Revolutionaries" },
  siu_edwardsville: { school: "SIU Edwardsville", nickname: "Cougars" },
  gardner_webb: { school: "Gardner-Webb", nickname: "Runnin' Bulldogs" },
  central_connecticut: { school: "Central Connecticut", nickname: "Blue Devils" },
  colorado_state: { school: "Colorado State", nickname: "Rams" },
  fairleigh_dickinson: { school: "Fairleigh Dickinson", nickname: "Knights" },
  miami_fl: { school: "Miami", nickname: "Hurricanes" },
  umkc: { school: "Kansas City", nickname: "Roos" },
  liu: { school: "Long Island", nickname: "Sharks" },
  st_josephs: { school: "St. Joseph's", nickname: "Hawks" },
  lindenwood: { school: "Lindenwood", nickname: "Lions" },
  georgia_southern: { school: "Georgia Southern", nickname: "Eagles" },
  ul_lafayette: { school: "UL Lafayette", nickname: "Ragin' Cajuns" },
  pittsburgh: { school: "Pittsburgh", nickname: "Panthers" },       // DB: pittsburgh → ESPN: pitt
  cleveland_state: { school: "Cleveland State", nickname: "Vikings" }, // DB: cleveland_state → ESPN: cleveland_st
  florida_gulf_coast: { school: "Florida Gulf Coast", nickname: "Eagles" }, // DB: florida_gulf_coast → ESPN: fgcu
  TBD: { school: "TBD", nickname: "Opponent TBD" },
  tba: { school: "TBA", nickname: "To Be Announced" },
};

/**
 * Get the school name and nickname for a given team slug.
 * Falls back to a formatted version of the slug if not found.
 */
export function getTeamName(slug: string): TeamName {
  if (DB_SLUG_NICKNAME_ALIASES[slug]) return DB_SLUG_NICKNAME_ALIASES[slug];
  if (TEAM_NAMES[slug]) return TEAM_NAMES[slug];
  // Fallback: format the slug as a title-cased school name
  const school = slug
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
  return { school, nickname: "" };
}
