/**
 * NCAAM team slug → { school, nickname } map.
 * Auto-generated from ESPN API (2026-03-04).
 * Covers all 362 NCAAM teams on ESPN.
 */

export interface TeamName {
  school: string;
  nickname: string;
}

export const TEAM_NAMES: Record<string, TeamName> = {
  abilene_chrstn: { school: "Abilene Chrstn", nickname: "Abilene Chrstn" },
  air_force: { school: "Air Force", nickname: "Air Force" },
  akron: { school: "Akron", nickname: "Akron" },
  alabama_am: { school: "Alabama A&M", nickname: "Alabama A&M" },
  alabama: { school: "Alabama", nickname: "Alabama" },
  alabama_st: { school: "Alabama St", nickname: "Alabama St" },
  alcorn_st: { school: "Alcorn St", nickname: "Alcorn St" },
  american: { school: "American", nickname: "American" },
  app_state: { school: "App State", nickname: "App State" },
  arizona_st: { school: "Arizona St", nickname: "Arizona St" },
  arizona: { school: "Arizona", nickname: "Arizona" },
  arkansas: { school: "Arkansas", nickname: "Arkansas" },
  arkansas_st: { school: "Arkansas St", nickname: "Arkansas St" },
  arpine_bluff: { school: "AR-Pine Bluff", nickname: "AR-Pine Bluff" },
  army: { school: "Army", nickname: "Army" },
  auburn: { school: "Auburn", nickname: "Auburn" },
  austin_peay: { school: "Austin Peay", nickname: "Austin Peay" },
  ball_state: { school: "Ball State", nickname: "Ball State" },
  baylor: { school: "Baylor", nickname: "Baylor" },
  bellarmine: { school: "Bellarmine", nickname: "Bellarmine" },
  belmont: { school: "Belmont", nickname: "Belmont" },
  bethune: { school: "Bethune", nickname: "Bethune" },
  binghamton: { school: "Binghamton", nickname: "Binghamton" },
  boise_st: { school: "Boise St", nickname: "Boise St" },
  boston_college: { school: "Boston College", nickname: "Boston College" },
  boston_u: { school: "Boston U", nickname: "Boston U" },
  bowling_green: { school: "Bowling Green", nickname: "Bowling Green" },
  bradley: { school: "Bradley", nickname: "Bradley" },
  brown: { school: "Brown", nickname: "Brown" },
  bryant: { school: "Bryant", nickname: "Bryant" },
  bucknell: { school: "Bucknell", nickname: "Bucknell" },
  buffalo: { school: "Buffalo", nickname: "Buffalo" },
  butler: { school: "Butler", nickname: "Butler" },
  byu: { school: "BYU", nickname: "BYU" },
  cal_poly: { school: "Cal Poly", nickname: "Cal Poly" },
  bakersfield: { school: "Bakersfield", nickname: "Bakersfield" },
  fullerton: { school: "Fullerton", nickname: "Fullerton" },
  csu_northridge: { school: "CSU Northridge", nickname: "CSU Northridge" },
  ca_baptist: { school: "CA Baptist", nickname: "CA Baptist" },
  california: { school: "California", nickname: "California" },
  campbell: { school: "Campbell", nickname: "Campbell" },
  canisius: { school: "Canisius", nickname: "Canisius" },
  c_arkansas: { school: "C Arkansas", nickname: "C Arkansas" },
  c_connecticut: { school: "C Connecticut", nickname: "C Connecticut" },
  c_michigan: { school: "C Michigan", nickname: "C Michigan" },
  charleston: { school: "Charleston", nickname: "Charleston" },
  charleston_so: { school: "Charleston So", nickname: "Charleston So" },
  charlotte: { school: "Charlotte", nickname: "Charlotte" },
  chattanooga: { school: "Chattanooga", nickname: "Chattanooga" },
  chicago_st: { school: "Chicago St", nickname: "Chicago St" },
  cincinnati: { school: "Cincinnati", nickname: "Cincinnati" },
  clemson: { school: "Clemson", nickname: "Clemson" },
  cleveland_st: { school: "Cleveland St", nickname: "Cleveland St" },
  coastal: { school: "Coastal", nickname: "Coastal" },
  colgate: { school: "Colgate", nickname: "Colgate" },
  colorado: { school: "Colorado", nickname: "Colorado" },
  colorado_st: { school: "Colorado St", nickname: "Colorado St" },
  columbia: { school: "Columbia", nickname: "Columbia" },
  coppin_st: { school: "Coppin St", nickname: "Coppin St" },
  cornell: { school: "Cornell", nickname: "Cornell" },
  creighton: { school: "Creighton", nickname: "Creighton" },
  dartmouth: { school: "Dartmouth", nickname: "Dartmouth" },
  davidson: { school: "Davidson", nickname: "Davidson" },
  dayton: { school: "Dayton", nickname: "Dayton" },
  delaware: { school: "Delaware", nickname: "Delaware" },
  delaware_st: { school: "Delaware St", nickname: "Delaware St" },
  denver: { school: "Denver", nickname: "Denver" },
  depaul: { school: "DePaul", nickname: "DePaul" },
  detroit_mercy: { school: "Detroit Mercy", nickname: "Detroit Mercy" },
  drake: { school: "Drake", nickname: "Drake" },
  drexel: { school: "Drexel", nickname: "Drexel" },
  duke: { school: "Duke", nickname: "Duke" },
  duquesne: { school: "Duquesne", nickname: "Duquesne" },
  east_carolina: { school: "East Carolina", nickname: "East Carolina" },
  etsu: { school: "ETSU", nickname: "ETSU" },
  e_texas_am: { school: "E Texas A&M", nickname: "E Texas A&M" },
  e_illinois: { school: "E Illinois", nickname: "E Illinois" },
  e_kentucky: { school: "E Kentucky", nickname: "E Kentucky" },
  e_michigan: { school: "E Michigan", nickname: "E Michigan" },
  e_washington: { school: "E Washington", nickname: "E Washington" },
  elon: { school: "Elon", nickname: "Elon" },
  evansville: { school: "Evansville", nickname: "Evansville" },
  fairfield: { school: "Fairfield", nickname: "Fairfield" },
  fdu: { school: "FDU", nickname: "FDU" },
  florida_am: { school: "Florida A&M", nickname: "Florida A&M" },
  fau: { school: "FAU", nickname: "FAU" },
  florida: { school: "Florida", nickname: "Florida" },
  fgcu: { school: "FGCU", nickname: "FGCU" },
  fiu: { school: "FIU", nickname: "FIU" },
  florida_st: { school: "Florida St", nickname: "Florida St" },
  fordham: { school: "Fordham", nickname: "Fordham" },
  fresno_st: { school: "Fresno St", nickname: "Fresno St" },
  furman: { school: "Furman", nickname: "Furman" },
  gardnerwebb: { school: "Gardner-Webb", nickname: "Gardner-Webb" },
  george_mason: { school: "George Mason", nickname: "George Mason" },
  g_washington: { school: "G Washington", nickname: "G Washington" },
  georgetown: { school: "Georgetown", nickname: "Georgetown" },
  georgia: { school: "Georgia", nickname: "Georgia" },
  ga_southern: { school: "GA Southern", nickname: "GA Southern" },
  georgia_st: { school: "Georgia St", nickname: "Georgia St" },
  georgia_tech: { school: "Georgia Tech", nickname: "Georgia Tech" },
  gonzaga: { school: "Gonzaga", nickname: "Gonzaga" },
  grambling: { school: "Grambling", nickname: "Grambling" },
  grand_canyon: { school: "Grand Canyon", nickname: "Grand Canyon" },
  green_bay: { school: "Green Bay", nickname: "Green Bay" },
  hampton: { school: "Hampton", nickname: "Hampton" },
  harvard: { school: "Harvard", nickname: "Harvard" },
  hawaii: { school: "Hawai’i", nickname: "Hawai’i" },
  high_point: { school: "High Point", nickname: "High Point" },
  hofstra: { school: "Hofstra", nickname: "Hofstra" },
  holy_cross: { school: "Holy Cross", nickname: "Holy Cross" },
  hou_christian: { school: "Hou Christian", nickname: "Hou Christian" },
  houston: { school: "Houston", nickname: "Houston" },
  howard: { school: "Howard", nickname: "Howard" },
  idaho_st: { school: "Idaho St", nickname: "Idaho St" },
  idaho: { school: "Idaho", nickname: "Idaho" },
  illinois: { school: "Illinois", nickname: "Illinois" },
  illinois_st: { school: "Illinois St", nickname: "Illinois St" },
  incarnate_word: { school: "Incarnate Word", nickname: "Incarnate Word" },
  indiana: { school: "Indiana", nickname: "Indiana" },
  indiana_st: { school: "Indiana St", nickname: "Indiana St" },
  iona: { school: "Iona", nickname: "Iona" },
  iowa: { school: "Iowa", nickname: "Iowa" },
  iowa_state: { school: "Iowa State", nickname: "Iowa State" },
  iu_indy: { school: "IU Indy", nickname: "IU Indy" },
  jackson_st: { school: "Jackson St", nickname: "Jackson St" },
  jacksonville: { school: "Jacksonville", nickname: "Jacksonville" },
  jax_state: { school: "Jax State", nickname: "Jax State" },
  james_madison: { school: "James Madison", nickname: "James Madison" },
  kansas_city: { school: "Kansas City", nickname: "Kansas City" },
  kansas: { school: "Kansas", nickname: "Kansas" },
  kansas_st: { school: "Kansas St", nickname: "Kansas St" },
  kennesaw_st: { school: "Kennesaw St", nickname: "Kennesaw St" },
  kent_state: { school: "Kent State", nickname: "Kent State" },
  kentucky: { school: "Kentucky", nickname: "Kentucky" },
  la_salle: { school: "La Salle", nickname: "La Salle" },
  lafayette: { school: "Lafayette", nickname: "Lafayette" },
  lamar: { school: "Lamar", nickname: "Lamar" },
  le_moyne: { school: "Le Moyne", nickname: "Le Moyne" },
  lehigh: { school: "Lehigh", nickname: "Lehigh" },
  liberty: { school: "Liberty", nickname: "Liberty" },
  lipscomb: { school: "Lipscomb", nickname: "Lipscomb" },
  little_rock: { school: "Little Rock", nickname: "Little Rock" },
  long_beach_st: { school: "Long Beach St", nickname: "Long Beach St" },
  long_island: { school: "Long Island", nickname: "Long Island" },
  longwood: { school: "Longwood", nickname: "Longwood" },
  louisiana: { school: "Louisiana", nickname: "Louisiana" },
  louisiana_tech: { school: "Louisiana Tech", nickname: "Louisiana Tech" },
  louisville: { school: "Louisville", nickname: "Louisville" },
  loyola_chicago: { school: "Loyola Chicago", nickname: "Loyola Chicago" },
  loyola_md: { school: "Loyola MD", nickname: "Loyola MD" },
  lmu: { school: "LMU", nickname: "LMU" },
  lsu: { school: "LSU", nickname: "LSU" },
  maine: { school: "Maine", nickname: "Maine" },
  manhattan: { school: "Manhattan", nickname: "Manhattan" },
  marist: { school: "Marist", nickname: "Marist" },
  marquette: { school: "Marquette", nickname: "Marquette" },
  marshall: { school: "Marshall", nickname: "Marshall" },
  md_eastern: { school: "MD Eastern", nickname: "MD Eastern" },
  maryland: { school: "Maryland", nickname: "Maryland" },
  umass: { school: "UMass", nickname: "UMass" },
  mcneese: { school: "McNeese", nickname: "McNeese" },
  memphis: { school: "Memphis", nickname: "Memphis" },
  mercer: { school: "Mercer", nickname: "Mercer" },
  mercyhurst: { school: "Mercyhurst", nickname: "Mercyhurst" },
  merrimack: { school: "Merrimack", nickname: "Merrimack" },
  miami_oh: { school: "Miami OH", nickname: "Miami OH" },
  miami: { school: "Miami", nickname: "Miami" },
  michigan_st: { school: "Michigan St", nickname: "Michigan St" },
  michigan: { school: "Michigan", nickname: "Michigan" },
  mtsu: { school: "MTSU", nickname: "MTSU" },
  milwaukee: { school: "Milwaukee", nickname: "Milwaukee" },
  minnesota: { school: "Minnesota", nickname: "Minnesota" },
  mississippi_st: { school: "Mississippi St", nickname: "Mississippi St" },
  miss_valley_st: { school: "Miss Valley St", nickname: "Miss Valley St" },
  missouri_st: { school: "Missouri St", nickname: "Missouri St" },
  missouri: { school: "Missouri", nickname: "Missouri" },
  monmouth: { school: "Monmouth", nickname: "Monmouth" },
  montana: { school: "Montana", nickname: "Montana" },
  montana_st: { school: "Montana St", nickname: "Montana St" },
  morehead_st: { school: "Morehead St", nickname: "Morehead St" },
  morgan_st: { school: "Morgan St", nickname: "Morgan St" },
  mount_st_marys: { school: "Mount St Marys", nickname: "Mount St Marys" },
  murray_st: { school: "Murray St", nickname: "Murray St" },
  navy: { school: "Navy", nickname: "Navy" },
  nc_state: { school: "NC State", nickname: "NC State" },
  nebraska: { school: "Nebraska", nickname: "Nebraska" },
  nevada: { school: "Nevada", nickname: "Nevada" },
  new_hampshire: { school: "New Hampshire", nickname: "New Hampshire" },
  new_haven: { school: "New Haven", nickname: "New Haven" },
  new_mexico: { school: "New Mexico", nickname: "New Mexico" },
  new_mexico_st: { school: "New Mexico St", nickname: "New Mexico St" },
  new_orleans: { school: "New Orleans", nickname: "New Orleans" },
  niagara: { school: "Niagara", nickname: "Niagara" },
  nicholls: { school: "Nicholls", nickname: "Nicholls" },
  njit: { school: "NJIT", nickname: "NJIT" },
  norfolk_st: { school: "Norfolk St", nickname: "Norfolk St" },
  north_alabama: { school: "North Alabama", nickname: "North Alabama" },
  nc_at: { school: "NC A&T", nickname: "NC A&T" },
  nc_central: { school: "NC Central", nickname: "NC Central" },
  north_carolina: { school: "North Carolina", nickname: "North Carolina" },
  north_dakota: { school: "North Dakota", nickname: "North Dakota" },
  n_dakota_st: { school: "N Dakota St", nickname: "N Dakota St" },
  north_florida: { school: "North Florida", nickname: "North Florida" },
  north_texas: { school: "North Texas", nickname: "North Texas" },
  northeastern: { school: "Northeastern", nickname: "Northeastern" },
  n_arizona: { school: "N Arizona", nickname: "N Arizona" },
  n_colorado: { school: "N Colorado", nickname: "N Colorado" },
  n_illinois: { school: "N Illinois", nickname: "N Illinois" },
  northern_iowa: { school: "Northern Iowa", nickname: "Northern Iowa" },
  n_kentucky: { school: "N Kentucky", nickname: "N Kentucky" },
  nwestern_st: { school: "N'Western St", nickname: "N'Western St" },
  northwestern: { school: "Northwestern", nickname: "Northwestern" },
  notre_dame: { school: "Notre Dame", nickname: "Notre Dame" },
  oakland: { school: "Oakland", nickname: "Oakland" },
  ohio: { school: "Ohio", nickname: "Ohio" },
  ohio_state: { school: "Ohio State", nickname: "Ohio State" },
  oklahoma: { school: "Oklahoma", nickname: "Oklahoma" },
  oklahoma_st: { school: "Oklahoma St", nickname: "Oklahoma St" },
  old_dominion: { school: "Old Dominion", nickname: "Old Dominion" },
  ole_miss: { school: "Ole Miss", nickname: "Ole Miss" },
  omaha: { school: "Omaha", nickname: "Omaha" },
  oral_roberts: { school: "Oral Roberts", nickname: "Oral Roberts" },
  oregon: { school: "Oregon", nickname: "Oregon" },
  oregon_st: { school: "Oregon St", nickname: "Oregon St" },
  pacific: { school: "Pacific", nickname: "Pacific" },
  penn_state: { school: "Penn State", nickname: "Penn State" },
  penn: { school: "Penn", nickname: "Penn" },
  pepperdine: { school: "Pepperdine", nickname: "Pepperdine" },
  pitt: { school: "Pitt", nickname: "Pitt" },
  portland: { school: "Portland", nickname: "Portland" },
  portland_st: { school: "Portland St", nickname: "Portland St" },
  prairie_view: { school: "Prairie View", nickname: "Prairie View" },
  presbyterian: { school: "Presbyterian", nickname: "Presbyterian" },
  princeton: { school: "Princeton", nickname: "Princeton" },
  providence: { school: "Providence", nickname: "Providence" },
  purdue: { school: "Purdue", nickname: "Purdue" },
  purdue_fw: { school: "Purdue FW", nickname: "Purdue FW" },
  quinnipiac: { school: "Quinnipiac", nickname: "Quinnipiac" },
  radford: { school: "Radford", nickname: "Radford" },
  rhode_island: { school: "Rhode Island", nickname: "Rhode Island" },
  rice: { school: "Rice", nickname: "Rice" },
  richmond: { school: "Richmond", nickname: "Richmond" },
  rider: { school: "Rider", nickname: "Rider" },
  robert_morris: { school: "Robert Morris", nickname: "Robert Morris" },
  rutgers: { school: "Rutgers", nickname: "Rutgers" },
  sacramento_st: { school: "Sacramento St", nickname: "Sacramento St" },
  sacred_heart: { school: "Sacred Heart", nickname: "Sacred Heart" },
  saint_francis: { school: "Saint Francis", nickname: "Saint Francis" },
  saint_josephs: { school: "Saint Joseph's", nickname: "Saint Joseph's" },
  saint_louis: { school: "Saint Louis", nickname: "Saint Louis" },
  saint_marys: { school: "Saint Mary's", nickname: "Saint Mary's" },
  saint_peters: { school: "Saint Peter's", nickname: "Saint Peter's" },
  sam_houston: { school: "Sam Houston", nickname: "Sam Houston" },
  samford: { school: "Samford", nickname: "Samford" },
  san_diego_st: { school: "San Diego St", nickname: "San Diego St" },
  san_diego: { school: "San Diego", nickname: "San Diego" },
  san_francisco: { school: "San Francisco", nickname: "San Francisco" },
  san_jos_st: { school: "San José St", nickname: "San José St" },
  santa_clara: { school: "Santa Clara", nickname: "Santa Clara" },
  se_louisiana: { school: "SE Louisiana", nickname: "SE Louisiana" },
  seattle_u: { school: "Seattle U", nickname: "Seattle U" },
  seton_hall: { school: "Seton Hall", nickname: "Seton Hall" },
  siena: { school: "Siena", nickname: "Siena" },
  siue: { school: "SIUE", nickname: "SIUE" },
  smu: { school: "SMU", nickname: "SMU" },
  south_alabama: { school: "South Alabama", nickname: "South Alabama" },
  south_carolina: { school: "South Carolina", nickname: "South Carolina" },
  sc_state: { school: "SC State", nickname: "SC State" },
  sc_upstate: { school: "SC Upstate", nickname: "SC Upstate" },
  south_dakota: { school: "South Dakota", nickname: "South Dakota" },
  s_dakota_st: { school: "S Dakota St", nickname: "S Dakota St" },
  south_florida: { school: "South Florida", nickname: "South Florida" },
  se_missouri: { school: "SE Missouri", nickname: "SE Missouri" },
  s_illinois: { school: "S Illinois", nickname: "S Illinois" },
  southern: { school: "Southern", nickname: "Southern" },
  southern_miss: { school: "Southern Miss", nickname: "Southern Miss" },
  southern_utah: { school: "Southern Utah", nickname: "Southern Utah" },
  st_bonaventure: { school: "St Bonaventure", nickname: "St Bonaventure" },
  st_johns: { school: "St John's", nickname: "St John's" },
  st_thomas_mn: { school: "St Thomas (MN)", nickname: "St Thomas (MN)" },
  stanford: { school: "Stanford", nickname: "Stanford" },
  sf_austin: { school: "SF Austin", nickname: "SF Austin" },
  stetson: { school: "Stetson", nickname: "Stetson" },
  stonehill: { school: "Stonehill", nickname: "Stonehill" },
  stony_brook: { school: "Stony Brook", nickname: "Stony Brook" },
  syracuse: { school: "Syracuse", nickname: "Syracuse" },
  tarleton_st: { school: "Tarleton St", nickname: "Tarleton St" },
  tcu: { school: "TCU", nickname: "TCU" },
  temple: { school: "Temple", nickname: "Temple" },
  tennessee_st: { school: "Tennessee St", nickname: "Tennessee St" },
  tennessee_tech: { school: "Tennessee Tech", nickname: "Tennessee Tech" },
  tennessee: { school: "Tennessee", nickname: "Tennessee" },
  texas_am: { school: "Texas A&M", nickname: "Texas A&M" },
  texas_amcc: { school: "Texas A&M-CC", nickname: "Texas A&M-CC" },
  texas: { school: "Texas", nickname: "Texas" },
  texas_southern: { school: "Texas Southern", nickname: "Texas Southern" },
  texas_st: { school: "Texas St", nickname: "Texas St" },
  texas_tech: { school: "Texas Tech", nickname: "Texas Tech" },
  the_citadel: { school: "The Citadel", nickname: "The Citadel" },
  toledo: { school: "Toledo", nickname: "Toledo" },
  towson: { school: "Towson", nickname: "Towson" },
  troy: { school: "Troy", nickname: "Troy" },
  tulane: { school: "Tulane", nickname: "Tulane" },
  tulsa: { school: "Tulsa", nickname: "Tulsa" },
  uab: { school: "UAB", nickname: "UAB" },
  ualbany: { school: "UAlbany", nickname: "UAlbany" },
  uc_davis: { school: "UC Davis", nickname: "UC Davis" },
  uc_irvine: { school: "UC Irvine", nickname: "UC Irvine" },
  uc_riverside: { school: "UC Riverside", nickname: "UC Riverside" },
  uc_san_diego: { school: "UC San Diego", nickname: "UC San Diego" },
  santa_barbara: { school: "Santa Barbara", nickname: "Santa Barbara" },
  ucf: { school: "UCF", nickname: "UCF" },
  ucla: { school: "UCLA", nickname: "UCLA" },
  uconn: { school: "UConn", nickname: "UConn" },
  uic: { school: "UIC", nickname: "UIC" },
  ul_monroe: { school: "UL Monroe", nickname: "UL Monroe" },
  umass_lowell: { school: "UMass Lowell", nickname: "UMass Lowell" },
  umbc: { school: "UMBC", nickname: "UMBC" },
  unc_asheville: { school: "UNC Asheville", nickname: "UNC Asheville" },
  unc_greensboro: { school: "UNC Greensboro", nickname: "UNC Greensboro" },
  unc_wilmington: { school: "UNC Wilmington", nickname: "UNC Wilmington" },
  unlv: { school: "UNLV", nickname: "UNLV" },
  usc: { school: "USC", nickname: "USC" },
  ut_arlington: { school: "UT Arlington", nickname: "UT Arlington" },
  ut_martin: { school: "UT Martin", nickname: "UT Martin" },
  ut_rio_grande: { school: "UT Rio Grande", nickname: "UT Rio Grande" },
  utah_state: { school: "Utah State", nickname: "Utah State" },
  utah_tech: { school: "Utah Tech", nickname: "Utah Tech" },
  utah: { school: "Utah", nickname: "Utah" },
  utah_valley: { school: "Utah Valley", nickname: "Utah Valley" },
  utep: { school: "UTEP", nickname: "UTEP" },
  utsa: { school: "UTSA", nickname: "UTSA" },
  valparaiso: { school: "Valparaiso", nickname: "Valparaiso" },
  vanderbilt: { school: "Vanderbilt", nickname: "Vanderbilt" },
  vcu: { school: "VCU", nickname: "VCU" },
  vermont: { school: "Vermont", nickname: "Vermont" },
  villanova: { school: "Villanova", nickname: "Villanova" },
  virginia: { school: "Virginia", nickname: "Virginia" },
  virginia_tech: { school: "Virginia Tech", nickname: "Virginia Tech" },
  vmi: { school: "VMI", nickname: "VMI" },
  wagner: { school: "Wagner", nickname: "Wagner" },
  wake_forest: { school: "Wake Forest", nickname: "Wake Forest" },
  washington: { school: "Washington", nickname: "Washington" },
  washington_st: { school: "Washington St", nickname: "Washington St" },
  weber_st: { school: "Weber St", nickname: "Weber St" },
  west_georgia: { school: "West Georgia", nickname: "West Georgia" },
  west_virginia: { school: "West Virginia", nickname: "West Virginia" },
  w_carolina: { school: "W Carolina", nickname: "W Carolina" },
  w_illinois: { school: "W Illinois", nickname: "W Illinois" },
  western_ky: { school: "Western KY", nickname: "Western KY" },
  w_michigan: { school: "W Michigan", nickname: "W Michigan" },
  wichita_st: { school: "Wichita St", nickname: "Wichita St" },
  william_mary: { school: "William & Mary", nickname: "William & Mary" },
  winthrop: { school: "Winthrop", nickname: "Winthrop" },
  wisconsin: { school: "Wisconsin", nickname: "Wisconsin" },
  wofford: { school: "Wofford", nickname: "Wofford" },
  wright_st: { school: "Wright St", nickname: "Wright St" },
  wyoming: { school: "Wyoming", nickname: "Wyoming" },
  xavier: { school: "Xavier", nickname: "Xavier" },
  yale: { school: "Yale", nickname: "Yale" },
  youngstown_st: { school: "Youngstown St", nickname: "Youngstown St" },
};

/**
 * Get the school name and nickname for a given team slug.
 * Falls back to a formatted version of the slug if not found.
 */
// DB slug aliases — maps DB-stored slugs to proper display names
const DB_SLUG_NICKNAME_ALIASES: Record<string, TeamName> = {
  florida_state: { school: "Florida State", nickname: "Seminoles" },
  chicago_state: { school: "Chicago State", nickname: "Cougars" },
  wright_state: { school: "Wright State", nickname: "Raiders" },
  youngstown_state: { school: "Youngstown State", nickname: "Penguins" },
  eastern_illinois: { school: "Eastern Illinois", nickname: "Panthers" },
  eastern_kentucky: { school: "Eastern Kentucky", nickname: "Colonels" },
  northern_kentucky: { school: "Northern Kentucky", nickname: "Norse" },
  south_carolina_upstate: { school: "SC Upstate", nickname: "Spartans" },
  george_washington: { school: "George Washington", nickname: "Revolutionaries" },
  siu_edwardsville: { school: "SIU Edwardsville", nickname: "Cougars" },
  gardner_webb: { school: "Gardner-Webb", nickname: "Runnin' Bulldogs" },
  central_connecticut: { school: "Central Connecticut", nickname: "Blue Devils" },
  colorado_state: { school: "Colorado State", nickname: "Rams" },
  fairleigh_dickinson: { school: "Fairleigh Dickinson", nickname: "Knights" },
  miami_fl: { school: "Miami", nickname: "Hurricanes" },
  umkc: { school: "Kansas City", nickname: "Roos" },
  liu: { school: "Long Island", nickname: "Sharks" },
  st_josephs: { school: "St. Joseph's", nickname: "Hawks" },
  lindenwood: { school: "Lindenwood", nickname: "Lions" },
  georgia_southern: { school: "Georgia Southern", nickname: "Eagles" },
  ul_lafayette: { school: "UL Lafayette", nickname: "Ragin' Cajuns" },
};

export function getTeamName(slug: string): TeamName {
  if (DB_SLUG_NICKNAME_ALIASES[slug]) return DB_SLUG_NICKNAME_ALIASES[slug];
  if (TEAM_NAMES[slug]) return TEAM_NAMES[slug];
  // Fallback: format the slug as a title-cased school name
  const school = slug
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
  return { school, nickname: "" };
}
