CREATE TABLE `mlb_lineups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`gameId` int NOT NULL,
	`scrapedAt` bigint NOT NULL,
	`awayPitcherName` varchar(128),
	`awayPitcherHand` varchar(4),
	`awayPitcherEra` varchar(32),
	`awayPitcherMlbamId` int,
	`awayPitcherConfirmed` boolean DEFAULT false,
	`homePitcherName` varchar(128),
	`homePitcherHand` varchar(4),
	`homePitcherEra` varchar(32),
	`homePitcherMlbamId` int,
	`homePitcherConfirmed` boolean DEFAULT false,
	`awayLineup` text,
	`homeLineup` text,
	`awayLineupConfirmed` boolean DEFAULT false,
	`homeLineupConfirmed` boolean DEFAULT false,
	`weatherIcon` varchar(8),
	`weatherTemp` varchar(16),
	`weatherWind` varchar(64),
	`weatherPrecip` int,
	`weatherDome` boolean DEFAULT false,
	`umpire` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mlb_lineups_id` PRIMARY KEY(`id`),
	CONSTRAINT `mlb_lineups_gameId_unique` UNIQUE(`gameId`)
);
