/**
 * Seed NCAAM team abbreviations into the ncaam_teams table.
 * Matches by vsinName (primary) then ncaaName (fallback).
 * Run: node scripts/seedAbbreviations.mjs
 */

import { createConnection } from "mysql2/promise";
import * as dotenv from "dotenv";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: join(__dirname, "../.env") });

// Full abbreviation list from user-provided data
const ABBREVS = [
  ["DUKE", "Duke"],
  ["UVA", "Virginia"],
  ["MIAFL", "Miami (FL)"],
  ["UNC", "North Carolina"],
  ["CLEM", "Clemson"],
  ["LOU", "Louisville"],
  ["NCST", "NC State"],
  ["CAL", "California"],
  ["FSU", "Florida St."],
  ["SMU", "SMU"],
  ["VT", "Virginia Tech"],
  ["STAN", "Stanford"],
  ["WAKE", "Wake Forest"],
  ["SYR", "Syracuse"],
  ["ND", "Notre Dame"],
  ["PITT", "Pittsburgh"],
  ["BC", "Boston College"],
  ["GT", "Georgia Tech"],
  ["UMBC", "UMBC"],
  ["UVM", "Vermont"],
  ["NJIT", "NJIT"],
  ["UML", "UMass Lowell"],
  ["UALB", "UAlbany"],
  ["ME", "Maine"],
  ["UNH", "New Hampshire"],
  ["BRY", "Bryant"],
  ["BING", "Binghamton"],
  ["USF", "South Fla."],
  ["WSU", "Wichita St."],
  ["TLSA", "Tulsa"],
  ["UAB", "UAB"],
  ["FAU", "Fla. Atlantic"],
  ["CHAR", "Charlotte"],
  ["TULN", "Tulane"],
  ["UNT", "North Texas"],
  ["TEM", "Temple"],
  ["MEM", "Memphis"],
  ["ECU", "East Carolina"],
  ["RICE", "Rice"],
  ["UTSA", "UTSA"],
  ["APSU", "Austin Peay"],
  ["UCA", "Central Ark."],
  ["QUEENS", "Queens (NC)"],
  ["LIP", "Lipscomb"],
  ["UWGA", "West Ga."],
  ["FGCU", "FGCU"],
  ["BELL", "Bellarmine"],
  ["STET", "Stetson"],
  ["JAX", "Jacksonville"],
  ["EKU", "Eastern Ky."],
  ["UNF", "North Florida"],
  ["UNA", "North Ala."],
  ["SLU", "Saint Louis"],
  ["VCU", "VCU"],
  ["DAY", "Dayton"],
  ["SJU", "Saint Joseph's"],
  ["GMU", "George Mason"],
  ["DAV", "Davidson"],
  ["GW", "George Washington"],
  ["DUQ", "Duquesne"],
  ["URI", "Rhode Island"],
  ["FOR", "Fordham"],
  ["RICH", "Richmond"],
  ["LAS", "La Salle"],
  ["SBU", "St. Bonaventure"],
  ["LOYCHI", "Loyola Chicago"],
  ["ARIZ", "Arizona"],
  ["HOU", "Houston"],
  ["TTU", "Texas Tech"],
  ["ISU", "Iowa St."],
  ["KU", "Kansas"],
  ["TCU", "TCU"],
  ["UCF", "UCF"],
  ["CIN", "Cincinnati"],
  ["BYU", "BYU"],
  ["WVU", "West Virginia"],
  ["COLO", "Colorado"],
  ["ASU", "Arizona St."],
  ["OKST", "Oklahoma St."],
  ["BAY", "Baylor"],
  ["KSU", "Kansas St."],
  ["UTAH", "Utah"],
  ["UCONN", "UConn"],
  ["STJ", "St. John's (NY)"],
  ["NOVA", "Villanova"],
  ["HALL", "Seton Hall"],
  ["CREI", "Creighton"],
  ["DEP", "DePaul"],
  ["PROV", "Providence"],
  ["BUT", "Butler"],
  ["XAV", "Xavier"],
  ["MARQ", "Marquette"],
  ["GTOWN", "Georgetown"],
  ["PSU", "Portland St."],
  ["MONTST", "Montana St."],
  ["EWU", "Eastern Wash."],
  ["UNCOL", "Northern Colo."],
  ["WEBER", "Weber St."],
  ["MONT", "Montana"],
  ["IDAHO", "Idaho"],
  ["SACST", "Sacramento St."],
  ["IDST", "Idaho St."],
  ["NAU", "Northern Ariz."],
  ["HPU", "High Point"],
  ["WIN", "Winthrop"],
  ["RAD", "Radford"],
  ["LONG", "Longwood"],
  ["UNCA", "UNC Asheville"],
  ["PRES", "Presbyterian"],
  ["CHSO", "Charleston So."],
  ["UPST", "USC Upstate"],
  ["GWU", "Gardner-Webb"],
  ["MICH", "Michigan"],
  ["MSU", "Michigan St."],
  ["NEB", "Nebraska"],
  ["ILL", "Illinois"],
  ["PUR", "Purdue"],
  ["WISC", "Wisconsin"],
  ["UCLA", "UCLA"],
  ["OSU", "Ohio St."],
  ["IOWA", "Iowa"],
  ["IND", "Indiana"],
  ["USC", "Southern California"],
  ["WASH", "Washington"],
  ["MINN", "Minnesota"],
  ["RUT", "Rutgers"],
  ["NW", "Northwestern"],
  ["ORE", "Oregon"],
  ["MD", "Maryland"],
  ["PSU2", "Penn St."],
  ["HAW", "Hawaii"],
  ["UCI", "UC Irvine"],
  ["UCSD", "UC San Diego"],
  ["CSUN", "CSUN"],
  ["UCSB", "UC Santa Barbara"],
  ["UCD", "UC Davis"],
  ["CSF", "Cal St. Fullerton"],
  ["CPOLY", "Cal Poly"],
  ["LBSU", "Long Beach St."],
  ["UCR", "UC Riverside"],
  ["CSUB", "CSU Bakersfield"],
  ["UNCW", "UNCW"],
  ["COC", "Col. of Charleston"],
  ["HOF", "Hofstra"],
  ["MONM", "Monmouth"],
  ["WM", "William & Mary"],
  ["DREX", "Drexel"],
  ["SBK", "Stony Brook"],
  ["TOW", "Towson"],
  ["CAMP", "Campbell"],
  ["HAM", "Hampton"],
  ["ELON", "Elon"],
  ["NCAT", "N.C. A&T"],
  ["NE", "Northeastern"],
  ["LIB", "Liberty"],
  ["SHSU", "Sam Houston"],
  ["WKU", "Western Ky."],
  ["KENN", "Kennesaw St."],
  ["LT", "Louisiana Tech"],
  ["MTSU", "Middle Tenn."],
  ["JAXST", "Jacksonville St."],
  ["FIU", "FIU"],
  ["MOST", "Missouri St."],
  ["NMSU", "New Mexico St."],
  ["UTEP", "UTEP"],
  ["DEL", "Delaware"],
  ["WRST", "Wright St."],
  ["RMU", "Robert Morris"],
  ["GB", "Green Bay"],
  ["DET", "Detroit Mercy"],
  ["OAK", "Oakland"],
  ["PFW", "Purdue Fort Wayne"],
  ["NKU", "Northern Ky."],
  ["YSU", "Youngstown St."],
  ["UWM", "Milwaukee"],
  ["CSU", "Cleveland St."],
  ["IUPUI", "IU Indy"],
  ["YALE", "Yale"],
  ["HARV", "Harvard"],
  ["PENN", "Penn"],
  ["COR", "Cornell"],
  ["COL", "Columbia"],
  ["DART", "Dartmouth"],
  ["PRIN", "Princeton"],
  ["BRN", "Brown"],
  ["MER", "Merrimack"],
  ["SPU", "Saint Peter's"],
  ["SIE", "Siena"],
  ["MARIST", "Marist"],
  ["QUIN", "Quinnipiac"],
  ["FAIR", "Fairfield"],
  ["MSM", "Mount St. Mary's"],
  ["IONA", "Iona"],
  ["SHU", "Sacred Heart"],
  ["MAN", "Manhattan"],
  ["CAN", "Canisius"],
  ["NIA", "Niagara"],
  ["RID", "Rider"],
  ["MIOH", "Miami (OH)"],
  ["AKR", "Akron"],
  ["KENT", "Kent St."],
  ["TOL", "Toledo"],
  ["OHIO", "Ohio"],
  ["BG", "Bowling Green"],
  ["BUF", "Buffalo"],
  ["UMASS", "Massachusetts"],
  ["BALL", "Ball St."],
  ["CMU", "Central Mich."],
  ["WMU", "Western Mich."],
  ["EMU", "Eastern Mich."],
  ["NIU", "NIU"],
  ["HOW", "Howard"],
  ["MORG", "Morgan St."],
  ["NORF", "Norfolk St."],
  ["NCCU", "N.C. Central"],
  ["SCSU", "South Carolina St."],
  ["UMES", "UMES"],
  ["COPP", "Coppin St."],
  ["DELST", "Delaware St."],
  ["USU", "Utah St."],
  ["UNM", "New Mexico"],
  ["SDSU", "San Diego St."],
  ["GCU", "Grand Canyon"],
  ["CSU2", "Colorado St."],
  ["BSU", "Boise St."],
  ["NEV", "Nevada"],
  ["UNLV", "UNLV"],
  ["WYO", "Wyoming"],
  ["FRES", "Fresno St."],
  ["SJSU", "San Jose St."],
  ["AFA", "Air Force"],
  ["BEL", "Belmont"],
  ["BRAD", "Bradley"],
  ["MURR", "Murray St."],
  ["ILST", "Illinois St."],
  ["UIC", "UIC"],
  ["UNI", "UNI"],
  ["VALPO", "Valparaiso"],
  ["SIU", "Southern Ill."],
  ["DRK", "Drake"],
  ["INST", "Indiana St."],
  ["EVAN", "Evansville"],
  ["LIU", "LIU"],
  ["CCSU", "Central Conn. St."],
  ["MERH", "Mercyhurst"],
  ["LEMOY", "Le Moyne"],
  ["NHVN", "New Haven"],
  ["WAG", "Wagner"],
  ["STNH", "Stonehill"],
  ["FDU", "FDU"],
  ["SFPA", "Saint Francis"],
  ["CHIST", "Chicago St."],
  ["TNST", "Tennessee St."],
  ["MORE", "Morehead St."],
  ["SEMO", "Southeast Mo. St."],
  ["UTM", "UT Martin"],
  ["SIUE", "SIUE"],
  ["LIN", "Lindenwood"],
  ["UALR", "Little Rock"],
  ["TTECH", "Tennessee Tech"],
  ["EIU", "Eastern Ill."],
  ["USI", "Southern Ind."],
  ["WIU", "Western Ill."],
  ["NAVY", "Navy"],
  ["COLG", "Colgate"],
  ["LEH", "Lehigh"],
  ["BU", "Boston U."],
  ["AMER", "American"],
  ["LOYMD", "Loyola Maryland"],
  ["LAF", "Lafayette"],
  ["BUCK", "Bucknell"],
  ["ARMY", "Army West Point"],
  ["HC", "Holy Cross"],
  ["FLA", "Florida"],
  ["BAMA", "Alabama"],
  ["ARK", "Arkansas"],
  ["TENN", "Tennessee"],
  ["VAND", "Vanderbilt"],
  ["TAMU", "Texas A&M"],
  ["MIZZ", "Missouri"],
  ["UK", "Kentucky"],
  ["UGA", "Georgia"],
  ["TEX", "Texas"],
  ["AUB", "Auburn"],
  ["OU", "Oklahoma"],
  ["MSST", "Mississippi St."],
  ["MISS", "Ole Miss"],
  ["LSU", "LSU"],
  ["SCAR", "South Carolina"],
  ["ETSU", "ETSU"],
  ["MER2", "Mercer"],
  ["WOF", "Wofford"],
  ["SAMF", "Samford"],
  ["FUR", "Furman"],
  ["WCU", "Western Caro."],
  ["UNCG", "UNC Greensboro"],
  ["CHAT", "Chattanooga"],
  ["CIT", "The Citadel"],
  ["VMI", "VMI"],
  ["SFA", "SFA"],
  ["MCN", "McNeese"],
  ["UTRGV", "UTRGV"],
  ["AMCC", "A&M-Corpus Christi"],
  ["UNO", "New Orleans"],
  ["NICH", "Nicholls"],
  ["HCU", "Houston Christian"],
  ["NWST", "Northwestern St."],
  ["UIW", "UIW"],
  ["LAM", "Lamar University"],
  ["ETAMU", "East Texas A&M"],
  ["SELA", "Southeastern La."],
  ["NDSU", "North Dakota St."],
  ["STT", "St. Thomas (MN)"],
  ["UND", "North Dakota"],
  ["USD", "South Dakota"],
  ["DEN", "Denver"],
  ["OMAHA", "Omaha"],
  ["SDSU2", "South Dakota St."],
  ["ORU", "Oral Roberts"],
  ["UMKC", "Kansas City"],
  ["TROY", "Troy"],
  ["USA", "South Alabama"],
  ["ARST", "Arkansas St."],
  ["MARSH", "Marshall"],
  ["TXST", "Texas St."],
  ["CCAR", "Coastal Carolina"],
  ["APP", "App State"],
  ["JMU", "James Madison"],
  ["USM", "Southern Miss."],
  ["GASO", "Ga. Southern"],
  ["ODU", "Old Dominion"],
  ["ULL", "Louisiana"],
  ["GAST", "Georgia St."],
  ["ULM", "ULM"],
  ["BCOOK", "Bethune-Cookman"],
  ["AAMU", "Alabama A&M"],
  ["SUBR", "Southern U."],
  ["FAMU", "Florida A&M"],
  ["TXSO", "Texas Southern"],
  ["UAPB", "Ark.-Pine Bluff"],
  ["JSU", "Jackson St."],
  ["PVAMU", "Prairie View"],
  ["ALST", "Alabama St."],
  ["ALCN", "Alcorn"],
  ["GRAM", "Grambling"],
  ["MVSU", "Mississippi Val."],
  ["UVU", "Utah Valley"],
  ["CBU", "California Baptist"],
  ["UTU", "Utah Tech"],
  ["UTA", "UT Arlington"],
  ["SUU", "Southern Utah"],
  ["ACU", "Abilene Christian"],
  ["TARL", "Tarleton St."],
  ["GONZ", "Gonzaga"],
  ["SMC", "Saint Mary's (CA)"],
  ["SCU", "Santa Clara"],
  ["ORST", "Oregon St."],
  ["SEAU", "Seattle U"],
  ["PAC", "Pacific"],
  ["USFCA", "San Francisco"],
  ["WSU2", "Washington St."],
  ["LMU", "LMU (CA)"],
  ["PORT", "Portland"],
  ["USD2", "San Diego"],
  ["PEPP", "Pepperdine"],
];

// Build a normalized name lookup: lowercase, remove punctuation
function normalize(name) {
  return name.toLowerCase().replace(/[^a-z0-9\s]/g, "").replace(/\s+/g, " ").trim();
}

async function main() {
  const conn = await createConnection(process.env.DATABASE_URL);

  // Fetch all teams from DB
  const [rows] = await conn.execute("SELECT id, vsinName, ncaaName FROM ncaam_teams");
  
  // Build lookup maps
  const byVsinName = new Map();
  const byNcaaName = new Map();
  for (const row of rows) {
    byVsinName.set(normalize(row.vsinName), row.id);
    byNcaaName.set(normalize(row.ncaaName), row.id);
  }

  let updated = 0;
  let notFound = [];

  for (const [abbrev, vsinDisplayName] of ABBREVS) {
    const key = normalize(vsinDisplayName);
    let id = byVsinName.get(key) ?? byNcaaName.get(key);
    
    if (!id) {
      notFound.push({ abbrev, vsinDisplayName });
      continue;
    }

    await conn.execute("UPDATE ncaam_teams SET abbrev = ? WHERE id = ?", [abbrev, id]);
    updated++;
  }

  console.log(`✅ Updated ${updated} teams with abbreviations`);
  if (notFound.length > 0) {
    console.log(`⚠️  Could not match ${notFound.length} teams:`);
    for (const { abbrev, vsinDisplayName } of notFound) {
      console.log(`   ${abbrev} → "${vsinDisplayName}"`);
    }
  }

  await conn.end();
}

main().catch(console.error);
